[package]
name = "realize-types"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
serde = {version = "1.0", features = ["derive"] }
thiserror = "2.0"
pathdiff = "0.2"

[dev-dependencies]
anyhow = "1.0" 