[package]
name = "realize-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
realize-lib = { path = "../realize-lib" }
anyhow = "1.0"
env_logger = "0.11"
nfsserve = "0.10.2"
async-trait = "0.1.88"
