[package]
name = "realize-control"
version = "0.1.0"
edition = "2024"

[dependencies]
realize-core = { path = "../realize-core" }
realize-network = { path = "../realize-network" }
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] } 