[peers.a]
address = "127.0.0.1:7001"
pubkey = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAPjsIFMiDLwPSdJ90P6Dh+jbpk/EoeorE+2OsdTzxX+s=
-----END PUBLIC KEY-----
"""

[peers.b]
address = "127.0.0.1:8001"
pubkey = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAZvriEx8hZEAildpfeifrv0Z5xED/kkK7wzT5Gel+w/w=
-----END PUBLIC KEY-----
"""
