name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'spec/**' 
      - 'docs/**'
      - '.cursor/**'
      - '.vscode/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'spec/**' 
      - 'docs/**' 
      - '.cursor/**'
      - '.vscode/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  on-linux:
    runs-on: ubuntu-24.04
    steps:
    - name: Install build dependencies
      run: "sudo apt-get install capnproto libcapnp-dev"
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Run tests
      run: "cargo test -- --skip :nfsmount:"
      
  on-macos:
    runs-on: macos-15
    steps:
    - name: Install build dependencies
      run: "brew install capnp"
    - uses: actions/checkout@v4
    - name: Build
      run: "cargo build"
    - name: Run tests
      run: "cargo test"
